config/routes.rb
Tweeter::Engine.routes.draw do
  resources :publishers do
    resources :tweets, only: [:index, :new, :create]
    resources :accounts, shallow: true
    resources :threads, shallow: true
  end
  
  resources :tweets, only: [:show, :edit, :update, :destroy] do
    member do
      get "publish" #post to twitter settings
    end
  end

  # resources :threads, only: [:show, :edit, :update, :destroy] do
  #   # member do
  #   #   get "publish" #post to twitter settings
  #   # end
  # end
end

app/models/tweeter/account.rb
module Tweeter
  class Account < ApplicationRecord
    belongs_to :publisher, class_name: Tweeter.publisher_class.to_s
    encrypts :api_key
    encrypts :api_key_secret
    encrypts :access_token
    encrypts :access_token_secret

    validates :api_key, presence: true
    validates :api_key_secret, presence: true
    validates :access_token, presence: true
    validates :access_token_secret, presence: true
    validates :publisher, presence: true
    validates :username, presence: true, uniqueness: { scope: :publisher_id }

    def get_credentials_hash 
      return { api_key: self.api_key, api_key_secret: self.api_key_secret, access_token: self.access_token, 
              access_token_secret: self.access_token_secret }
    end

    # before_validation :set_publisher

    # private
    #   def set_publisher
    #     self.publisher = Tweeter.publisher_class.constantize.find_or_create_by()
    #   end

  end
end

app/models/tweeter/application_record.rb
module Tweeter
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/tweeter/thread.rb
module Tweeter
  class Thread < ApplicationRecord
    belongs_to :publisher, class_name: Tweeter.publisher_class.to_s
    has_many :tweets, dependent: :destroy # , before_add: :set_tweet_sequence


    # def get_last_sequence_number 
    #   self.tweets.by_thread_sequence.last.sequence + 1
    # end

    def get_next_sequence_number(previous_tweet=nil)
      if previous_tweet
        # If a previous tweet is provided, update the sequence of tweets after that
        thread_tweets = self.tweets.by_thread_sequence.where("sequence > ?", previous_tweet.sequence)
        thread_tweets.each do |tweet|
          tweet.sequence += 1
          tweet.save
        end
        return previous_tweet.sequence + 1
      else # no previous tweet provided
        return self.tweets.by_thread_sequence.last.sequence + 1
      end
 
    end

    # def set_tweet_sequence(tweet) 
    #   # tweet.sequence = self.get_next_sequence_number
    #   puts "------------------------------------"
    #   tweet.update(sequence: self.get_next_sequence_number)
    # end

    # def publish_now 
      
    # end

    # def publish_later 
    #   self.job_id += 1
    #   if self.published_at 
    #     self.status = "scheduled"
    #     self.save
    #     PostTweetJob.set(wait_until: self.published_at).perform_later(self, self.job_id)
    #     return true
    #   end      
    # end
  end
end

app/models/tweeter/tweet.rb
module Tweeter
  class Tweet < ApplicationRecord
    before_validation :add_tweet_to_thread
    has_one_attached :image

    belongs_to :publisher, class_name: Tweeter.publisher_class.to_s
    belongs_to :thread
    
    enum :status, draft: 0, scheduled: 1, published: 2, failed: 3
  
    scope :latest, -> { order(updated_at: :desc) }
    scope :by_publised_at, -> { order( published_at: :asc) }
    scope :lead_tweet, -> { where(sequence: 1) }
    scope :by_thread_sequence, -> { order(sequence: :asc) }

    def post_to_twitter(reply_to: "")
      x_credentials = self.publisher.twitter_account.get_credentials_hash
      x_client = X::Client.new(**x_credentials)
      tweet_body = {text: self.content}
      if self.image.representable?
        media_category = "tweet_image" # other options are: dm_image or subtitles; for videos or GIFs use chunked_upload  
        #Rails.error.handle do
          self.image.open do |image_file|
            media = ::X::MediaUploader.upload(client: x_client, file_path: image_file.path, media_category: media_category)
            tweet_body[:media] = {media_ids: [media["media_id_string"]]}
          end
        #end
      end
      if !reply_to.empty?
        tweet_body[:reply] = {in_reply_to_tweet_id: reply_to}
      end
      # puts "---------------------------------------------"
      # puts tweet_body
      # puts reply_to
      post = x_client.post("tweets", tweet_body.to_json)
      return post
    end
  
    def schedule_tweet 
      self.job_id += 1
      if self.published_at 
        self.status = "scheduled"
        self.save
        PostTweetJob.set(wait_until: self.published_at).perform_later(self, self.job_id)
        return true
      end
    end
  
    def publish_now 
      self.published_at = nil
      self.job_id += 1
      self.status = "scheduled"
      self.save
      PostTweetJob.perform_later(self, self.job_id)
      return true
    end

    def publish_later
      if self.published_at.nil?
        self.published_at = Time.now + 5.minutes # default to 5 minutes from now
      end
      self.job_id += 1
      self.status = "scheduled"
      self.save
      PostTweetJob.set(wait_until: self.published_at).perform_later(self, self.job_id)
      return true 
    end

    def is_lead_tweet? 
      if self.sequence == 1
        return true
      else
        return false
      end
    end

    private
      def add_tweet_to_thread 
        # if self.thread
        #   self.sequence = self.thread.get_next_sequence_number
        # else # Create new thread, if thread does not exists.
        #   self.thread = Thread.create(publisher: self.publisher)
        # end
        self.thread = self.thread || Thread.create(publisher: self.publisher)
      end

  end


end

app/controllers/tweeter/accounts_controller.rb
module Tweeter
  class AccountsController < ::ApplicationController
    layout "tweeter"
    before_action :set_account, only: %i[ show edit update destroy ]

    # GET /accounts
    def index
      # @newsletter = Newsletter.find(params[:newsletter_id])
      # @accounts = Account.all
    end

    # GET /accounts/1
    def show

    end

    # GET /accounts/new
    def new
      @publisher = Tweeter.publisher_class.find(params[:publisher_id])
      @account = Account.new
      @account.publisher = @publisher
      # if @account.save
      #   redirect_to edit_account_path @account, notice: "Account was successfully created."
      # end
    end

    # GET /accounts/1/edit
    def edit
    end

    # POST /accounts
    def create
      @account = Account.new(account_params)
      @publisher = Tweeter.publisher_class.find(params[:publisher_id])
      @account.publisher = @publisher
      if @account.save
        redirect_to account_path(@account), notice: "Account was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /accounts/1
    def update
      if @account.update(account_params)
        redirect_to @account, notice: "Account was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /accounts/1
    def destroy
      @account.destroy!
      redirect_to accounts_path, notice: "Account was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_account
        @account = Account.find(params.expect(:id))
        @publisher = @account.publisher
      end

      # Only allow a list of trusted parameters through.
      def account_params
        params.expect(account: [ :username, :api_key, :api_key_secret, :access_token, :access_token_secret ])
      end
  end
end

app/controllers/tweeter/application_controller.rb
module Tweeter
  class ApplicationController < ::ActionController::Base
  # class ApplicationController < ::ApplicationController

  end
end

app/controllers/tweeter/threads_controller.rb
module Tweeter
  class ThreadsController < ::ApplicationController
    layout "tweeter"
    before_action :set_thread, only: %i[ update publish destroy ]

    def update 
      if @thread.update(thread_params)
        if params[:commit] == "Post to Twitter"
          redirect_to publish_thread_path(@thread)
        elsif params[:commit] == "Schedule" && @thread.publish_later
          redirect_to tweet_path(@thread.tweet), notice: "The thread scheduled at #{@tweet.published_at}"
        elsif params[:commit] == "Post now" && @thread.publish_now
          redirect_to tweet_path(@tweet), notice: "CloudQubes is posting the tweet in the background"
        elsif params[:commit] == "Unpublish"
          redirect_to edit_tweet_path(@tweet)     
        else
          
        end
      end
    end

    def destroy 
      if @thread.destroy
        redirect_to publisher_tweets_path(@publisher, status: "draft"), notice: "Thread was successfully deleted."
      end
    end

    def publish 
      
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_thread
        @thread = Thread.find(params.expect(:id))
        @publisher = @thread.publisher
      end

      def thread_params 
        params.expect(thread: [ :published_at ])
      end

  end
end

app/controllers/tweeter/tweets_controller.rb
module Tweeter
  class TweetsController < ::ApplicationController
    layout "tweeter"
    before_action :set_tweet, only: %i[ show edit update publish destroy ]
    around_action :switch_time_zone, only: %i[ edit update publish index show ]


    # GET /tweets
    def index
      @publisher = Tweeter.publisher_class.find(params[:publisher_id])
      # @tweets = @publisher.tweets
      # @selected = params[:status] #To apply the CSS to the selected tab
      if params[:status]
        @selected = params[:status] #To apply the CSS to the selected tab
        if @selected == "scheduled"
          @tweets = @publisher.tweets.by_publised_at.where(status: @selected)
        else
          @tweets = @publisher.tweets.lead_tweet.latest.where(status: @selected)
        end
      else
        @tweets = @publisher.tweets.latest
      end
    end

    # GET /tweets/1
    def show
    end

    # GET /tweets/new
    def new
      @tweet = Tweet.new

    end

    # GET /tweets/1/edit
    def edit
    end

    # POST /tweets
    def create
      @tweet = Tweet.new(tweet_params)
      @publisher = @tweet.publisher
      if @tweet.thread 
        @previous_tweet = Tweet.find_by(id: params.dig(:previous_tweet_id)) || @tweet.thread.tweets.by_thread_sequence.last
        @tweet.sequence = @tweet.thread.get_next_sequence_number(@previous_tweet)
        # @tweet.thread.update_sequence(@tweet, previous_tweet)
      end
      
      if @tweet.save
        if @tweet.sequence > 1 # subsequent tweets belonging to  a thread
          render 'create'
        else
          redirect_to tweet_path @tweet, notice: "Tweet was successfully created."
        end
      # else
      #   #todo: Give an error response if could not create
      #   render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /tweets/1
    def update
      if @tweet.update(tweet_params)
        if params[:commit] == "Save"
          # redirect_to edit_tweet_path(@tweet), notice: "Saved at #{@tweet.updated_at}"
          # redirect_to tweet_path(@tweet)
          render "update"
        elsif params[:commit] == "Publish now"
          if @tweet.publish_now
            redirect_to tweet_path(@tweet)
          end
        elsif params[:commit] == "Publish later"
          if @tweet.publish_later
            redirect_to tweet_path(@tweet), notice: "Tweet scheduled for #{@tweet.published_at}"
          else
            render :edit, status: :unprocessable_entity
          end
        else # Cancel
          redirect_to publisher_tweets_path(@tweet.publisher, status: "draft")
        end
      else
        render :edit, status: :unprocessable_entity
      end
  
    end

    def publish 
      
    end

    # DELETE /tweets/1
    def destroy
      @tweet.destroy!
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_tweet
        @tweet = Tweet.find(params.expect(:id))
        @publisher = @tweet.publisher
      end

      # Only allow a list of trusted parameters through.
      def tweet_params
        params.expect(tweet: [ :content, :publisher_id, :published_at, :thread_id, :image ])
      end
  end
end

app/helpers/tweeter/accounts_helper.rb
module Tweeter
  module AccountsHelper
  end
end

app/helpers/tweeter/application_helper.rb
module Tweeter
  module ApplicationHelper
  end
end

app/helpers/tweeter/threads_helper.rb
module Tweeter
  module ThreadsHelper
  end
end

app/helpers/tweeter/tweets_helper.rb
module Tweeter
  module TweetsHelper

    def tweet_content(tweet)
      if tweet.content && !tweet.content.empty?
        return simple_format tweet.content
      else
        return "Blank tweet"
      end
    end
  end
end

app/views/tweeter/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="top-border">
    <%= form.textarea :content, class: 'small-textarea-field-with-border',
    data: {controller: "tweet-length", action: "input -> tweet-length#countTweetChars" } %>
    <div class="status-bar">
      <span id="char-count"></span>
    </div>
  </div>
  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image, accept: "image/*", class: "file-input" %>
    <% if tweet.image.representable? %>
      <div class="image-preview">
        <%= image_tag main_app.url_for(tweet.image), class: "mini-thumbnail" %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit "Save", class: 'grey-button' %>
  </div>
<% end %>
<div>
  <%= button_to "Delete tweet", tweet, method: :delete, form: { data: { turbo_confirm: 'Delete tweet?',
                                                                        turbo_confirm_confirm_label: "Yes, delete",
                                                                        turbo_confirm_cancel_label: "No, go back" } },
                                                        class: "danger-button" %>
</div>

app/views/tweeter/tweets/_tweet.html.erb
<div>
  <div class="flex-space-between">
    <div class="tweet-content">
      <%= tweet_content(tweet) %>
    </div>
    <div>
      <% if tweet.image.representable? %>
        <%= image_tag main_app.url_for(tweet.image), class: "tweet-image-thumbnail" %>
      <% end %>
    </div>
  </div>

  <div class="top-space-point-5 meta-text">
    <% if tweet.draft? %>
      Updated <%= time_ago_in_words tweet.updated_at %> ago
    <% elsif tweet.scheduled? %>
      <% if tweet.published_at %>
        <p class="meta-text">Will be posted at <%= tweet.published_at.strftime("%H:%M, %d %b, %Y") %></p>
      <% else %>
        <p class="meta-text">Cloudqubes is posting this tweet in the background.</p>
      <% end %>
    <% elsif tweet.failed? %>
      <p class="meta-text">Sending failed.</p>
    <% else %>
      <% if tweet.published_at %>
        <p class="meta-text">Posted to Twitter at <%= tweet.published_at.strftime("%H:%M, %d %b, %Y") %></p>
      <% end %>
    <% end %>
  </div>

</div>

app/views/tweeter/tweets/create.turbo_stream.erb
<%= turbo_stream.after @previous_tweet do %>
  <%= turbo_frame_tag @tweet do %>
    <%= render partial: "form", locals: { tweet: @tweet } %>
  <% end %>
<% end %>

app/views/tweeter/tweets/destroy.turbo_stream.erb
<%= turbo_stream.remove @tweet do %>

<% end %>

app/views/tweeter/tweets/edit.html.erb
<p style="color: green"><%= notice %></p>


<%= turbo_frame_tag "thread" do %>

      <%= turbo_frame_tag @tweet do %>
        <%= render "form", tweet: @tweet %>
      <% end %>  
<% end %>

app/views/tweeter/tweets/index.html.erb
<% if notice %>
  <p style="color: green"><%= notice %></p>
<% end %>

<% content_for :title, "Tweets" %>
<section >
  
  <div class="">
    <div class="bottom-space-point-5">
      <div>
        <%= button_to "Write tweet", publisher_tweets_path(@publisher), params: {tweet: {publisher_id: @publisher}}, method: :post, class: "create-button" %>
      </div>      
    </div>
    <div class="top-space-point-5 bottom-space-point-5 flex-left-gap-point-5">
      <div>
        <%= link_to "Drafts", tweeter.publisher_tweets_path(@publisher, status: "draft"), class: class_names("tab", {selected_tab: @selected == "draft"}) %>
      </div>
      <div>
        <%= link_to "scheduled", tweeter.publisher_tweets_path(@publisher, status: "scheduled"), class: class_names("tab", {selected_tab: @selected == "scheduled"}) %>
      </div>
      <div>
        <%= link_to "Published", tweeter.publisher_tweets_path(@publisher, status: "published"), class: class_names("tab", {selected_tab: @selected == "published"}) %>
      </div>
      <div>
        <%= link_to "Failed", tweeter.publisher_tweets_path(@publisher, status: "failed"), class: class_names("tab", {selected_tab: @selected == "failed"}) %>
      </div>      
    </div>

  </div>

</section>


</section>
<section>
  <div id="tweets">
    <% if @tweets %>
    <% @tweets.each do |tweet| %>
      <div class="top-border bottom-space-point-5">
        <%= render tweet %>
          <div class="meta-text">
            <% if tweet.thread.tweets.count == 1 %>
              <%= tweet.thread.tweets.count %> tweet in thread
            <% else %>
              <%= tweet.thread.tweets.count %> tweets in thread
            <% end %>
          </div>
        <div class="top-space-point-5">
          <%= link_to "View thread", tweet %>
        </div>        
      </div>

    <% end %>
    <% end %>
  </div>
</section>

app/views/tweeter/tweets/new.html.erb
<% content_for :title, "New tweet" %>

<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweeter/tweets/publish.html.erb
<h1 class="l4-header top-space-1 bottom-space-1">You are going to post this to Twitter</h1>



  <%= form_with(model: [@tweet]) do |form| %>

    <div>
      <%= form.label :published_at, "Schedule date" %>
      <%= form.datetime_local_field :published_at %>
    </div>
    <div class="top-space-2 bottom-space-1">
      
      <%= form.submit "Post now" %>
      <%= form.submit "Schedule" %>
      <%= form.submit "Cancel" %>
    </div>
  <% end %>

  <div class="bottom-space-1">
    <%= @tweet.content %>
  </div>

app/views/tweeter/tweets/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="bottom-space-1">
  <div class="bottom-space-1">
    <%= button_to "Delete thread", @tweet.thread, method: :delete, form: { data: { turbo_confirm: 'Delete entire thread?',
                                                                          turbo_confirm_confirm_label: "Yes, delete",
                                                                          turbo_confirm_cancel_label: "No, go back" } },
                                                                  class: "danger-button" %>
    
  </div>
  <%= form_with model: @tweet do |form| %>
    <div class="bottom-space-1">
      <%= form.label :published_at, "Publish at" %>
      <%= form.datetime_local_field :published_at %>
    </div>
    <div class="bottom-space-1">
      <%= form.submit "Publish later" %>
      <%= form.submit "Publish now" %>        
    </div>
  <% end %>
</div>

<%= turbo_frame_tag @tweet.thread do %>

  <% @tweet.thread.tweets.by_thread_sequence.each do |tweet| %>
    <%= turbo_frame_tag tweet do %>
      <div class="top-border bottom-space-point-5">
        <%= render tweet %>
      </div>
      <div class="flex-left-gap-point-5 bottom-space-point-5 top-space-point-5">
        <%= link_to "Edit", edit_tweet_path(tweet), class: "grey-button-small" %>
        <%= button_to "Add tweet below", publisher_tweets_path(tweet.publisher), params: {tweet: {publisher_id: tweet.publisher, thread_id: tweet.thread}, previous_tweet_id: tweet.id}, method: :post, class: "grey-button-small" %>
      </div>
    <% end %> 

  <% end %>
<% end %>

app/views/tweeter/tweets/show.turbo_stream.erb
<%= turbo_stream.replace @tweet, @tweet %>

app/views/tweeter/tweets/test.turbo_stream.erb
<%= turbo_stream.replace @tweet, @tweet %>

app/views/tweeter/tweets/update.turbo_stream.erb
<%= turbo_stream.replace @tweet do %>
  <%= turbo_frame_tag @tweet do %>
    <div class="top-border bottom-space-point-5">
      <%= render partial: "tweet", locals: { tweet: @tweet } %>       
    </div>
      <div class="flex-left-gap-point-5 bottom-space-point-5 top-space-point-5">
        <%= link_to "Edit", edit_tweet_path(@tweet), class: "grey-button-small" %>
        <%= button_to "Add tweet below", publisher_tweets_path(@tweet.publisher), params: {tweet: {publisher_id: @tweet.publisher, thread_id: @tweet.thread}, previous_tweet_id: @tweet.id}, method: :post, class: "grey-button-small" %>
      </div>
  <% end %>
<% end %>